### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#42]
I adjusted my configuration file to include 0 transformers, _i.e._: `num_transformers: 0`.

I then get a division by zero error when running `pvrpm`:

```
$ poetry run pvrpm run --case ./ --threads 0 ./richland.yaml 
2022-02-19 13:08:44,421--WARNING: There is a non-zero value in the fixed annual O&M costs input. These will be overwritten with the new values.
2022-02-19 13:08:44,421--WARNING: Degradation is set by the PVRPM script, you have entered a non-zero degradation to the degradation input. This script will set the degradation input to zero.
Traceback (most recent call last):
  File "/home/bthayer/.cache/pypoetry/virtualenvs/pvrpm-review-SED2OxlJ-py3.10/bin/pvrpm", line 8, in <module>
    sys.exit(main())
  File "/home/bthayer/.cache/pypoetry/virtualenvs/pvrpm-review-SED2OxlJ-py3.10/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/bthayer/.cache/pypoetry/virtualenvs/pvrpm-review-SED2OxlJ-py3.10/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/bthayer/.cache/pypoetry/virtualenvs/pvrpm-review-SED2OxlJ-py3.10/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bthayer/.cache/pypoetry/virtualenvs/pvrpm-review-SED2OxlJ-py3.10/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bthayer/.cache/pypoetry/virtualenvs/pvrpm-review-SED2OxlJ-py3.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/bthayer/.cache/pypoetry/virtualenvs/pvrpm-review-SED2OxlJ-py3.10/lib/python3.9/site-packages/pvrpm/__main__.py", line 55, in run
    sam_case = SamCase(case, config, num_realizations=int(realization), results_folder=results)
  File "/home/bthayer/.cache/pypoetry/virtualenvs/pvrpm-review-SED2OxlJ-py3.10/lib/python3.9/site-packages/pvrpm/core/case.py", line 70, in __init__
    self.__verify_case()
  File "/home/bthayer/.cache/pypoetry/virtualenvs/pvrpm-review-SED2OxlJ-py3.10/lib/python3.9/site-packages/pvrpm/core/case.py", line 580, in __verify_case
    self.config[ck.INVERTER_PER_TRANS] = int(np.floor(self.num_inverters / self.config[ck.NUM_TRANSFORMERS]))
ZeroDivisionError: float division by zero
```

It looks like this occurs during case verification - it's probably worth adding a `try` / `except ZeroDivisionError` block to provide users 
with an actionable error message, *e.g.*, "The number of transformers (n_transformers) must be >= 1."

**Comment by brandons209** [comment]
Fixed in a098c23e4f051e1a9f7099464984b2ec3331c258
