### ISSUE TITLE
[FEATURE] <Support for SAM 2022.11.21>

### ISSUE THREAD

**Issue by HannanSolo** [FSEC-Photovoltaics/pvrpm-lcoe#64]
Currently, PVRPM crashed when using a configuration from SAM 2022.11.21

When I try to verify using the same configuration YAML, but different SAM project json I get the error below.

```
Traceback (most recent call last):
  File "/home/hannansolo/.local/bin/pvrpm", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/hannansolo/.local/lib/python3.10/site-packages/pvrpm/__main__.py", line 104, in verify
    sam_case = SamCase(case, config)
  File "/home/hannansolo/.local/lib/python3.10/site-packages/pvrpm/core/case.py", line 27, in __init__
    self.modules = self.__load_modules()
  File "/home/hannansolo/.local/lib/python3.10/site-packages/pvrpm/core/case.py", line 142, in __load_modules
    module.value(k, v)
Exception: Value must be numeric
```
It would be nice to have it support the newest version.

Thank you for everything you do! :)

**Comment by brandons209** [comment]
Yes, currently PVRPM only works with SAM version 2021.12.02.

I'll update it to the latest version soon!

**Comment by brandons209** [comment]
Alright, PVRPM is updated to the latest version! You can do `pip install -U pvrpm-lcoe` to update to version 1.8.0.
